/**
 * build-ooxml.mjs — 将 @silurus/ooxml 的 dist 文件复制到 vendor 目录
 *
 * 功能：
 *   1. 复制所有文件（.mjs / .js / .wasm / .d.ts）到静态资源目录
 *   2. 为 .wasm 文件创建内容 hash 命名的副本，用于强缓存
 *   3. 生成 wasm-manifest.mjs，供桥接层传入 wasmUrl
 *
 * 输出到: src/main/resources/static/js/vendor/ooxml/
 *
 * 用法: node scripts/build-ooxml.mjs
 */

import fs from 'fs'
import path from 'path'
import crypto from 'crypto'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const root = path.resolve(__dirname, '..')

const SRC = path.join(root, 'node_modules/@silurus/ooxml/dist')
const DST = path.join(root, 'src/main/resources/static/js/vendor/ooxml')

// 确保目标目录存在
fs.mkdirSync(DST, { recursive: true })

// 复制所有文件（.mjs / .js / .wasm / .d.ts）
let count = 0
for (const file of fs.readdirSync(SRC)) {
  const srcFile = path.join(SRC, file)
  const dstFile = path.join(DST, file)
  if (fs.statSync(srcFile).isFile()) {
    fs.cpSync(srcFile, dstFile, { force: true })
    count++
    console.log(`  ✓ ${file}`)
  }
}

// 也复制 types 目录
const typesSrc = path.join(SRC, 'types')
const typesDst = path.join(DST, 'types')
if (fs.existsSync(typesSrc)) {
  fs.cpSync(typesSrc, typesDst, { recursive: true, force: true })
  console.log(`  ✓ types/ (directory)`)
}

// ── WASM 内容 hash 副本 + manifest ──
// 为每个 .wasm 文件创建带内容 hash 的副本（如 pptx_parser_bg.a1b2c3d4.wasm）
// 这样浏览器可以安全地强缓存（Cache-Control: immutable），
// 内容变化时文件名变化自动失效。
const WASM_REGEX = /^(pptx|docx|xlsx)_parser_bg\.wasm$/
const manifest = {}

for (const file of fs.readdirSync(SRC)) {
  const match = file.match(WASM_REGEX)
  if (!match) continue

  const format = match[1] // pptx | docx | xlsx
  const srcFile = path.join(SRC, file)
  const content = fs.readFileSync(srcFile)
  const hash = crypto.createHash('sha256').update(content).digest('hex').slice(0, 16)
  const hashedName = `${format}_parser_bg.${hash}.wasm`

  fs.cpSync(srcFile, path.join(DST, hashedName), { force: true })
  manifest[format] = hashedName
  console.log(`  ➕ ${hashedName} (hash:${hash})`)
}

// 写入 wasm-manifest.mjs（ESM 模块，可被桥接层静态导入）
const manifestCode =
  '// auto-generated by build-ooxml.mjs — DO NOT EDIT\n' +
  'const manifest = ' + JSON.stringify(manifest, null, 2) + ';\n' +
  'export default manifest;\n'

fs.writeFileSync(path.join(DST, 'wasm-manifest.mjs'), manifestCode, 'utf-8')
console.log(`  📋 wasm-manifest.mjs`)

console.log(`\n✅ @silurus/ooxml 已复制到 js/vendor/ooxml/ (${count} 个文件, ${Object.keys(manifest).length} 个 WASM hash 副本)`)
